### PR TITLE
Add simple installer

### PR DESCRIPTION
**Pull request by framps**
This simple installer doesn't require folks to fiddle with git to install shrink-backup. shrink-backup will be installed with a simple curl call :-)

### CODE REVIEW

**Comment by framps** [comment]
> You are going to hate me for this...

Nope. It's just a suggestion and you have to decide to accept or reject it.

> Could you explain what your thought process is as to why a git clone is not enough?
> Why is a curl superior to git?

I provided this tiny installer already in another project. It was accepted BUT the author described in the doc two ways to install the tool: Either to use the curl call or execute various steps which actually are executed in the install script. That way folks like you who find a curl call with a pipe into bash evil can download your script, set the execution rights and move the script in some directory which is included. in PATH. The others just execute the curl call to install a tool which is much more convenient.

I noticed there are a lot of folks out there who started to use a Raspberry for various things like HomeAutomation, AdBlocking et al. They are not used with the command line and are happy they got their system setup. Now they want to crate a backup just in case something went wrong. They prefer to be able to install a tool in a convenient way and not fiddle with github/git (what's this ???).

You now will reply - everybody who works on Linux has to have basic understanding of commands to be useful in the command line. I see your concern - I'm with you - but if you check you will find a lot of tools which pipe a curl result into bash when there is something to be installed. The install script is very easy to read. A user who want's to call shrink-backup as root will have much more problems to understand the code :wink:

**Comment by framps** [comment]
> **Edit**
> I might be a bit slow to answer, a bit of health issues here..

Take your time and get well again.

Just a comment: You are used to edit comments and mark them with **Edit**. But that way I  miss your update because I don't get an update notification of an existing comment - unfortunately - and I usually don't reread a previous comment :cry: Maybe this is a root of our misunderstanding.

**Comment by UnconnectedBedna** [comment]
Oh, yeah, I prefer editing over making multiple posts, and yes, I suppose you have to read here rather than the email.. xD

I'm still not sure...

`curl https://raw.githubusercontent.com/UnconnectedBedna/shrink-backup/master/install | sudo bash`
vs
`git clone https://github.com/UnconnectedBedna/shrink-backup`
Or even:
`wget http:shrinkbackup-yadayadayada -o /some/path`

3 lines, both look pretty confusing to a new linux user imho.
The difference with not using git is the user is NOT in a situation I am assuming if they were to make a bug report... No excludefile available for example (if using curl).

How does the user upgrade this compared to typing `git pull` and be done?

The execution bit of the script is not set in the repo, that could arguably be different though.

> The install script is very easy to read. A user who want's to call shrink-backup as root will have much more problems to understand the code 😉

Not sure what you mean by that, you pipe curl into sudo bash, a `git clone` is/can be done by the user without sudo...
And the script has to be started as root or it will exit with an error.
And if the user has to download the script, open it in a reader, check what it does and THEN run it with bash, well, how is that easier than typing `git clone`?

> I noticed there are a lot of folks out there who started to use a Raspberry for various things like HomeAutomation, AdBlocking et al. They are not used with the command line and are happy they got their system setup. Now they want to create a backup just in case something went wrong. They prefer to be able to install a tool in a convenient way and not fiddle with github/git (what's this ???).

We almost started ww3 over this, but this is a mentality issue for me. xD
Me doing that feels like me belittling the user, I would NEVER do that.
"The user is uneducated so here is an installer to hold their hand". We are talking about a git clone here, not super complicated...

I would rather EDUCATE the user than just doing things for them. Does that make sense? (I AM "working" on a wiki entry)
I do NOT want to do what rpiOS does when expanding the partition using `raspi-config`, I respect my users too much if you see what I mean.

The location of the script does not matter. If it's in `$PATH`, great, but it is not a requirement. Starting it with an absolute path, a relative path or directly from $PATH, should not matter at all.

> You now will reply - everybody who works on Linux has to have basic understanding of commands to be useful in the command line.

Well, no, not in my opinion. But if you change that to "everybody who **uses this script** on Linux has to have basic understanding of commands". xD

There is also a link directly to the tar file in the release directly at the top of the github repo README.MD.
Works just like on windows: Click link, click save/open, unpack to wherever you want. This version has execution bit set so no need for `cmod +x`.

I am far from convinced, but you made some pretty valid points, but still not enough to accept the PR.. Sry, but I will keep thinking about this, because the fact you, an experienced user think this is a good idea DOES mean quite a bit to me honestly, don't get me wrong, I AM reading and thinking.
Maybe there are other things that can be done better in this regard.

I have actually started to write a little bit for the wiki about how git works. Cloning, switching branches, updating (maybe even `git stash`), but never got further than reorganizing the wiki to make better space for wider information outside shrink-backup.

**Comment by framps** [comment]
> Oh, yeah, I prefer editing over making multiple posts, and yes, I suppose you have to read here rather than the email.. xD

I usually don't read the notification eMail. I use the embedded link to open the new post and read it. As far as I remember a couple of days ago we both were online (looks like we're in the same timezone :-) ) and I got a notification - opened your post and read it. Next day I answered but didn't reread your post which you edited in the mean time. Therefore I missed you update :-(.

> 3 lines, all look pretty confusing to a new linux user imho.

Agree. But the main difference is the second and third one require additional commands to be executed if the tool should be installed. I agree after a clone or wget shrink-backup can be invoked with `sudo ./shrink-backup`. 

> How does the user upgrade this compared to typing `git pull` and be done?

Just use curl again. You don't have just a single file which has to be updated. raspiBackup consists of multiple files including config files which will be overwritten with curl. That's why raspiBackup has an upgrade option which makes sure new config options will be merged into the existing configuration file and a backup is created to easily revert the upgrade if something doesn't work any more.

> would rather EDUCATE the user than just doing things for them. Does that make sense?

Yes. I agree. If you want to spend time for a Wiki that's definitely the better way. 

> The location of the script does not matter. If it's in `$PATH`, great, but it is not a requirement. Starting it with an absolute path, a relative path or directly from $PATH, should not matter at all.

Agree. But it's common to move any tools into and common directories included in $PATH.

> I have actually started to write a little bit for the wiki about how git works. Cloning, switching branches, updating (maybe even `git stash`),

If you want to spent your time on this that's great. But I frankly wouldn't do this. That's something a developer needs to know and he will already know. Then just document the commands to execute to install shrink-backup, wget, mv and chown to root.

> Maybe there are other things that can be done better in this regard.

You can add another option in shrink-backup which will move shrink-backup in some directory included in $PATH ;-) But if shrink-backup is going to be included in some distro they will use apt or some other SW installation and maintenance tool. 

> could link to a gist or smthn, that has this script that the user can use, but I put a BIG DISCLAIMER that I DO NOT think running curl directly from the internet is a good idea, but if the user wants, they can use this as a super easy install solution (and a link to a gist or smthn) to get it into your $PATH and set execution bit.

I don't have problem to create a PR on your testing branch instead. But frankly I think if somebody reads your BIG DISCLAIMER the script will not be used. If you use a more general statement like `Alternatively, you can manually install from source if you don't trust the curl | sudo bash install script` the installation script will be used.

**Comment by UnconnectedBedna** [comment]
> Agree. But the main difference is the second and third one require additional commands to be executed if the tool should be installed. I agree after a clone or wget shrink-backup can be invoked with sudo ./shrink-backup.

Not if I make the file executable on the git repo..

> Just use curl again. You don't have just a single file which has to be updated. raspiBackup consists of multiple files including config files which will be overwritten with curl. That's why raspiBackup has an upgrade option which makes sure new config options will be merged into the existing configuration file and a backup is created to easily revert the upgrade if something doesn't work any more.

I use `.gitignore` for that, because there is only one single file that the user might edit, `exclude.txt` so that has to be managed.
I'm not perticluarly interested in the ability to revert. A user can do that by just going back to an older version of the repo and use that curl command, that would work right? Or is githubusercontent ONLY the latest somehow? (I do not know how that works)

> Yes. I agree. If you want to spend time for a Wiki that's definitely the better way.

There is the mentality difference between us, I DO think that is the better way.

> If you want to spent your time on this that's great. But I frankly wouldn't do this. That's something a developer needs to know and he will already know. Then just document the commands to execute to install shrink-backup, wget, mv and chown to root.

It's not for a developer, again, it's for the USER to LEARN if things are unclear for them. These things are not _that_ complicated. :smile: 
I don't have any documentation directed towards devs, I AM that document.. xD

> Agree. But it's common to move any tools into and common directories included in $PATH.

Yes, and I will cover that in the wiki, again, teaching instead of holding hand.
I just realized I don't actually mention this anywhere, but the script is supposed to be 100% portable, I should include that on the readme. That is why I create the logfile and have the config file in the same directory.
That is also one of the reasons I am a bit against installing it in /usr.

> You can add another option in shrink-backup which will move shrink-backup in some directory included in $PATH ;-) But if shrink-backup is going to be included in some distro they will use apt or some other SW installation and maintenance tool.

Oh, no the distro thing will be a completely different thing, it's own repo I create and then we get that into the repo. I probably won't even fork this project, I own the code so whatever I need I can just copy paste however I want. :)
And that will obv be installed into correct system user directory, IIRC when I looked it was in /usr/bin

> I don't have problem to create a PR on your testing branch instead. But frankly I think if somebody reads your BIG DISCLAIMER the script will not be used. If you use a more general statement like Alternatively, you can manually install from source if you don't trust the curl | sudo bash install script the installation script will be used.

That was what I was thinking of yes, but the disclaimer would not say not to use this version, it would say something like "generally do not ever run curl into sudo bash from the internet unless you KNOW what is ran or you trust the source 100%." IDK...

But you are actually starting to convince me, but there are things that might make this not great.

The script would have to also be modified to KNOW that it got installed with curl, not git or the tar file.
1. Log file should go into `/var/log`
2. `exclude.txt` should go into `/etc`
3. `exclude.txt` have to be merged, or ignored at update because user might have made changes.

So this is probably easiest made by the install script changing a variable with `sed` or smthn and then I would have to change paths inside the script depending on what that variable is set to. Not a huge deal tbh but it has to be made.

This makes the script "non-portable" so I also have to make the user aware that they have to use different methods of updating depending on how they installed.
Not necessarily better over all...

Thoughts?

**Comment by framps** [comment]
> I'm north of you, the dudes with horns on our helmets if you know what I mean. xD

I've been in Stockholm already. It's a nice town - but it getting dark soon in autumn :-(

> Not if I make the file executable on the github repo..

:+1: 

> I'm not particularly interested in the ability to revert. A user can do that by just going back to an older version of the repo and use that curl command, that would work right?

Well - than the curl call will become much more complicated because you have to tag your releases carefully and use the git API to retrieve any version. But that's overkill.

> Or is githubusercontent ONLY the latest somehow?

Yes. 

> I DO think that is the better way

:+1: 

> That is why I create the logfile and have the config file in the same directory.

Tools on Linux usually place the executable in /usr/bin or /usr/sbin or /usr/local/bin and configs in /etc or /etc/local. That's what I also do with raspiBackup. But the log file is created in $CWD, the directory the user invokes the tool. 
I use /usr/local/bin and /usr/local/etc for all tools I install from github. That way I can easily copy the directory contents to a new system whenever I upgrade my system to a new OS release and I don't have to clone all the git repos of these tools again. 
To evaluate a tool it's great to have everything at one place. 

> That was what I was thinking of yes, but the disclaimer would not say not to use this version, it would say something like "generally do not ever run curl into sudo bash from the internet unless you KNOW what is ran or you trust the source 100%." IDK...

Ok. So I misunderstand you. You will warn the user `curl | bash` is dangerous but for your tool it's not :-D

> But you are actually starting to convince me

I'm frankly not keen to convince you ... I just want to show you a way users can install you nice script in a convenient way :-) Whether you accept my proposal or reject it - up to you :-)

> The script would have to also be modified to KNOW that it got installed with curl, not git or the tar file.

I frankly wasn't aware of the exclude.txt file. So I backed up everything when I evaluated your script. I saw in there are the common directories you don't need to backup. Why don't you just hard code these directories in your script and don't provide an exclude.txt file in your repo. That way you don't have to fiddle with any merges of the contents when somebody upgrades. /var/log will be used for the log (or $CWD maybe?) and therefore your script doesn't have to know where it's located. 

> 5\. I want the script to be installed in it's own directory so the license can be provided there.

> Path is probably best to `/usr/local/bin/shrink-backup` and then symlink to that. (I am unsure here, but I think you have to symlink if it's in subdir?)

This will work. I think it's sufficient to have the license in github. 

> So this is probably easiest made by the install script changing a variable in the script

If you stick with your current approach to have a dedicated exclude.txt in the directory your script is located in that will work. I frankly wouldn't change any code during the installation. Instead a EXPORT variable in .bashrc can be used or some config file in /etc but is overkill for me. If you hard code the default exclude.txt contents in your script and use $CMD as the log file location you don't have to update anything ;-) Please note: I don't want to force you to accept my proposals. Just think about them :-)

> Not a huge deal tbh but it has to be made. `INSTALL_METHOD='curl'` to follow the variable naming standard in the script.
> 
> This makes the script "non-portable" so I also have to make the user aware that they have to use different methods of updating depending on how they installed.

I didn't check you code and thus I don't understand your statement `non-portable`. I checked you README multiple times - but as far as I can see there are installation instructions missing. They maybe would help me to understand your `non-portable` statement. Anybody familiar with git and Linux will know what to do to use shrink-backup. But as I already mentioned there a lot of folks out there which use a Raspberry (you see I'm just talking about Raspberry users only) and are not that familiar with git and Linux.

**Comment by UnconnectedBedna** [comment]
> Well - than the curl call will become much more complicated because you have to tag your releases carefully and use the git API to retrieve any version. But that's overkill.

When creating the release, just also create the tag, I have done since the beginning of this project.
So if I git clone the repo, then `git checkout origin` you should be in tag "v1.1", if that makes sense.
How to incorporate that in the curl, I have no idea.
But never the less, I'm not very interested in implementing it, the latest version is what is provided, otherwise the user have to use git.

> Ok. So I misunderstand you. You will warn the user curl | bash is dangerous but for your tool it's not :-D

Pretty much yeah, it's about trust. I will try explain that.
it's rooted in my bonemarrow not to do things like that without reading every single line of code that is about to run.
To me it's the same thing as not executing some random exe file from the internet on windows...
But the wording wont be as harsh as you want to make it.. xD

> I frankly wasn't aware of the exclude.txt file. So I backed up everything when I evaluated your script. I saw in there are the common directories you don't need to backup. Why don't you just hard code these directories in your script and don't provide an exclude.txt file in your repo. That way you don't have to fiddle with any merges of the contents when somebody upgrades. /var/log will be used for the log (or $CWD maybe?) and therefore your script doesn't have to know where it's located.

Please read [this](https://github.com/UnconnectedBedna/shrink-backup?tab=readme-ov-file#-t-excludetxt)
I give the user the possibility to include or exclude whatever they want, removing the file would remove that possibility.
The file is not necessary unless you use the option `-t`.

> I didn't check you code and thus I don't understand your statement non-portable. I checked you README multiple times - but as far as I can see there are installation instructions missing

Because there is nothing to install, the script is portable. Portable means you do NOT have to install anything and you can run it from wherever you want.
I should probably mention that in the readme. Becomes even more relevant if this is to be implemented.

Linux standard is to be used. so logs goes into `/var/log`, configs goes into `/etc` and the binary (or sh in this situation) goes into `/usr/local/bin` (could also go into sbin) because it is installed locally after installation of operating system.
That way there is absolutely no need to add anything to any path in `.bashrc` or anything simlar. :)
But as I said, the script is constructed in such way that this is a non issue, all that has to be done is change the variable with `sed` as I mentioned earlier.

**Comment by framps** [comment]
> But never the less, I'm not very interested in implementing it, the latest version is what is provided, otherwise the user have to use git.

:+1: 

> But the wording wont be as harsh as you want to make it..

:+1: 

... OOPS ... you just updated the previous post ... I fortunately saw the update from git in my browser ... 

Will reflect your updates in next post :-)

**Comment by framps** [comment]
> Because there is nothing to install, the script is portable.

I agree. Folks who know Linux well know what they have to do.

But just a couple of minutes ago in the German forum rpi-clone was suggested to use to a user who is very nervous to use a command line tool to create a backup with rpi-clone. Another user chimed in and told him - just use the `curl ... install | bash` call and then invoke rpi-clone. If you check you'll see the install script for rpi-clone was provided by me :-D. And this was not the first user to lose his fear of downloading and installing a tool from github ;-). 

I'll create a new PR with the updates you asked for in your testing branch.

**Comment by UnconnectedBedna** [comment]
Now we are getting somewhere! :)

BUT, the pr is still on main, that will never happen. xD

> [ramps](https://github.com/framps) wants to merge 7 commits into [UnconnectedBedna:main](https://github.com/UnconnectedBedna/shrink-backup/tree/main) from [framps:install](https://github.com/framps/shrink-backup/tree/install)

There are also typos and a few other things, but rather than starting commenting on them here, it would probably be better if you closed this commit (or maybe I have to) and remake it by creating the files on the testing branch.

Main is ONLY for tested releases, witch this will become after it has been tested properly, but I think it mostly looks good otherwise.

**Comment by UnconnectedBedna** [comment]
Moved over to #43

**Pull request closed without merging**
