### PR TITLE
Simple installer

### PR DESCRIPTION
**Pull request by framps**
As discussed a new PR into testing :-)

### CODE REVIEW

**Review by UnconnectedBedna — CHANGES_REQUESTED** [review]
Can we change the name to `installer.sh` "that would be greaaat" *zips coffee*

**Review by UnconnectedBedna — CHANGES_REQUESTED** [review]
Please move the variable to below line 124 where all the other default variables are defined.

And make it `INSTALL_METHOD='default'` (note the single quotes, I only use " if there is a changable variable involved so the `sed` line will have to be changed too.

Typo on line 29:
> `echo "$PACKAGE_FILE usccessfully installed"`

I see you already thought of the name of the license file AND the location, way better than what I suggested. Thanks.

**Comment by framps** [comment]
> can you please add the suffix `.license`

I'm sorry but I don't understand what you want me to do with .license :-(

**Comment by UnconnectedBedna** [comment]
```diff
- readonly DIR_LICENSE="/usr/share/doc/$PACKAGE_FILE"
+ readonly DIR_LICENSE="/usr/share/doc/${PACKAGE_FILE}.license"
```

And also pull the README.MD from the repo and put that in `/usr/share/doc/` but rename it to `shrink-backup.md`

**Comment by framps** [comment]
> ```diff
> readonly DIR_LICENSE="/usr/share/doc/${PACKAGE_FILE}.license"
> ```

Then you don't follow the naming rules of /usr/share/doc because you don't use the toolname as directory. :-(

**Comment by UnconnectedBedna** [comment]
Wait, im a fkn idiot, that is not what you are doing.. LMAO.
NOW I see what you mean by renaming does not make sense.. You create a DIRECTORY in `/usr/share/doc` xD

I have been playing satisfactory, my brain is broken.. :wink: 

Just keep it LICENSE and README.MD... I am so sorry!

**Comment by framps** [comment]
> I am so sorry!

No problem :-) Keep in mind you finally have to update the two first constants to refer to your repo and your tesing branch when you accept the PR. I had to define my repo there to execute tests.

**Review by UnconnectedBedna — APPROVED** [review]
I think this all looks good.
Unless you want to keep fiddling with it some more, I am good to merge for testing purposes.

**Comment by UnconnectedBedna** [comment]
> Keep in mind you finally have to update the two first constants to refer to your repo and your tesing branch when you accept the PR. I had to define my repo there to execute tests.

Yeah I saw that, but we keep it for now, it's an easy change in the future.

**Review by UnconnectedBedna — APPROVED** [review]
This dude is spoonfeeding me. I like it. xD

**Comment by UnconnectedBedna** [comment]
I am just waiting for your confirmation to merge, because I do not want to push my commits before you are done, might create unnecessary conflicts.

**Comment by framps** [comment]
I'm fine now.

**Comment by UnconnectedBedna** [comment]
Thank you so much for this.
Make sure to pull latest changes since I just pushed them https://github.com/UnconnectedBedna/shrink-backup/commit/d7c85d20cedb6d53940d698a382b288370ee6186

**Comment by framps** [comment]
You're welcome. Glad I was able to help :-)

Let me know if there is something missing or even wrong and I will add or fix this.

**Comment by framps** [comment]
> Make sure to pull latest changes since I just pushed them

Done

**Pull request merged**
